# Generated by Django 5.2.3 on 2025-06-23 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_task_description_en_task_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskhistory",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Task History",
                "verbose_name_plural": "Task Histories",
            },
        ),
    ]
