# Generated by Django 5.2.3 on 2025-06-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="task.group"
            ),
        ),
    ]
